function init() {
    $('#dj-main-munebar').html(' ');
    document.writeln("<!DOCTYPE html>");
    document.writeln("<html lang=\'en\'>");
    document.writeln("<head>");
    document.writeln("    <meta charset=\'UTF-8\'>");
    document.writeln("    <title>通用主菜单</title>");
    document.writeln("    <link rel=\'stylesheet\' href=\'lib/bootstrap-4.3.1-dist/css/bootstrap.css\'>");
    document.writeln("<!--    <link rel=\'stylesheet\' href=\'css/dj-general.css\'>-->");
    document.writeln("    <link rel=\'stylesheet\' href=\'lib/fontawesome/css/all.css\'>");
    document.writeln("    <link rel=\'stylesheet\' href=\'css/dj-general-black.css\'>");
    document.writeln("</head>");
    document.writeln("<body>");
    document.writeln("");
    document.writeln("<div class=\'dj-general-menu container-fluid\'>");
    document.writeln("    <nav class=\'navbar navbar-expand-lg navbar-light  dj-main-general container\'>");
    document.writeln("        <a class=\'navbar-brand\' href=\'#\'>");
    document.writeln("            <img src=\'dj-img/globalheader_logo.png\' height=\'44\' width=\'176\'/>");
    document.writeln("        </a>");
    document.writeln("        <div class=\'collapse navbar-collapse dj-general-menubr\' >");
    document.writeln("            <ul class=\'navbar-nav mr-auto\'>");
    document.writeln("                <li class=\'nav-item\' id=\'dj-general-shoptitle\'>");
    document.writeln("                    <a class=\'nav-link\' href=\'#\' >商店<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                    <ul class=\'nav shadow\' id=\'dj-general-shop\'>");
    document.writeln("                        <li  class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>精选<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>探索<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>鉴赏家<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>愿望单<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>新闻<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>统计<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                    </ul>");
    document.writeln("                </li>");
    document.writeln("                <li class=\'nav-item\' id=\'dj-general-communitytitle\'>");
    document.writeln("                    <a class=\'nav-link\' href=\'#\'>社区</a>");
    document.writeln("                    <ul class=\'nav shadow\' id=\'dj-general-community\'>");
    document.writeln("                        <li  class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>精选<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>探索<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>鉴赏家<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>愿望单<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>新闻<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\'nav-item\'>");
    document.writeln("                            <a class=\'nav-link\' href=\'#\'>统计<span class=\'sr-only\'>(current)</span></a>");
    document.writeln("                        </li>");
    document.writeln("                    </ul>");
    document.writeln("                </li>");
    document.writeln("                <li class=\'nav-item\'>");
    document.writeln("                    <a class=\'nav-link\' href=\'#\'>关于</a>");
    document.writeln("                </li>");
    document.writeln("                <li class=\'nav-item\'>");
    document.writeln("                    <a class=\'nav-link\' href=\'#\'>客服</a>");
    document.writeln("                </li>");
    document.writeln("            </ul>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'collapse navbar-collapse \' id=\'dj-general-seMenubar\'>");
    document.writeln("            <ul class=\'navbar-nav mr-auto\' >");
    document.writeln("                <li class=\'nav-item\'><a href=\'\' class=\'nav-link\' id=\'dj-general-download\'><i class=\'fa fa-download\' style=\'margin-right: 10px\'></i>安装 steam</a></li>");
    document.writeln("                <li class=\'nav-item\'><a href=\'\' class=\'nav-link\'>登录</a></li>");
    document.writeln("                <li class=\'nav-item\'>");
    document.writeln("                    <a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'dj-general-language\' role=\'button\' data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
    document.writeln("                    语言");
    document.writeln("                </a>");
    document.writeln("                    <div class=\'dropdown-menu shadow\'  aria-labelledby=\'navbarDropdown\'>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>繁體中文(繁体中文)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>日本語(日语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>就亏叶(韩语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>lns(泰语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>6bnrapCkm (保加利亚语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Cestina (捷克语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Dansk (丹麦语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Deutsch (德语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>English (英语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Espanol- Espana (西班牙语-西班牙)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Espanol - Latinoamerica (西班牙语拉J美洲)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>EXηVIka (希腊语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Francais (法语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Italiano (意大利语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Magyar (匈牙利语)</a>");
    document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Nederlands (荷兰语)</a>");
    document.writeln("                    </div>");
    document.writeln("                </li>");
    document.writeln("");
    document.writeln("            </ul>");
    document.writeln("        </div>");
    document.writeln("    </nav>");
    document.writeln("</div>");
    document.writeln("");
    document.writeln("<div class=\'dj-general-second-menu container-fluid\'></div>");
    document.writeln("<script src=\'lib/jQuery/jQuery.js\'></script>");
    document.writeln("<script src=\'lib/bootstrap-4.3.1-dist/js/bootstrap.js\'></script>");
    document.writeln("<script src=\'lib/bootstrap-4.3.1-dist/js/bootstrap.bundle.js\'></script>");
    document.writeln("</body>");
    document.writeln("</html>");
}
window.setInterval(init,300);