document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>通用二级主菜单</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'lib/bootstrap-4.3.1-dist/css/bootstrap.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/dj-general.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'lib/fontawesome/css/all.css\'>");
document.writeln("<!--    <link rel=\'stylesheet\' href=\'css/dj-general-secondMenu.css\'>-->");
document.writeln("    <link rel=\'stylesheet\' href=\'css/dj-general-secondMenu-black.css\'>");
document.writeln("");
document.writeln("</head>");
document.writeln("<body style=\'overflow: hidden\'>");
document.writeln("");
document.writeln("<div class=\'dj-general-second-menu container-fluid\'>");
document.writeln("    <nav class=\' dj-general-second-main-menu container navbar navbar-expand-lg navbar-light\'>");
document.writeln("        <div class=\'navbar-collapse\' id=\'navbarNav\'>");
document.writeln("            <ul class=\'navbar-nav rounded shadow-sm\'>");
document.writeln("                <li class=\'nav-item active\' id=\'dj-gsmm-shop\'>");
document.writeln("                    <a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'navbarDropdown\' role=\'button\'");
document.writeln("                       data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                        您的商店");
document.writeln("                    </a>");
document.writeln("                    <div class=\'dropdown-menu shadow hidden\'>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>商店主页</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>最近查看过的</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Steam鉴赏家</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>最近更新</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\' id=\'dj-gsmm-game\'>");
document.writeln("                    <a class=\'nav-link dropdown-toggle\' href=\'#\' role=\'button\' data-toggle=\'dropdown\'");
document.writeln("                       aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                        游戏");
document.writeln("                    </a>");
document.writeln("                    <div class=\'dropdown-menu shadow hidden\'>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>免费游玩</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>抢先体验</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>试玩</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>虚拟现实</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>支持Steam控制器</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Steam上的网吧游戏</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>远程畅玩</a>");
document.writeln("                        <div class=\'dropdown-divider\'></div>");
document.writeln("                        <h6 class=\'dropdown-header\'>按类型浏览:</h6>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>休闲</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>体育</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>冒险</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>动作</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>大型多人在线</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>模拟</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>独立</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>竞速</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>策略</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>角色扮演</a>");
document.writeln("                        <div class=\'dropdown-divider\'></div>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>查看热门标签</a>");
document.writeln("                        <div class=\'dropdown-divider\'></div>");
document.writeln("                        <h6 class=\'dropdown-header\'>按平台浏览:</h6>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Mac OS X</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>SteamOS + Linux</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item collapse navbar-collapse\' id=\'dj-gsmm-software\'>");
document.writeln("                    <a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'navbardrop\' role=\'button\' data-toggle=\'dropdown\'");
document.writeln("                       aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                        软件");
document.writeln("                    </a>");
document.writeln("                    <div class=\'dropdown-menu shadow hidden\'>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>软件中心</a>");
document.writeln("                        <div href=\'\' class=\'dropdown-divider\'></div>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>动画制作和建模</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>实用工具</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>教育</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>游戏开发</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>照片编辑</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>网络出版</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>视频制作</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>设计与插画</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>音频制作</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item collapse navbar-collapse\' id=\'dj-gsmm-hardware\'>");
document.writeln("                    <a class=\'nav-link dropdown-toggle\' href=\'#\' role=\'button\' data-toggle=\'dropdown\'");
document.writeln("                       aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                        硬件");
document.writeln("                    </a>");
document.writeln("                    <div class=\'dropdown-menu shadow hidden\'>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Valve Index@</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Steam控制器</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>Steam流式盒</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>HTC Vive</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'#\'>新闻</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'#\'>Steam 实验室</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item dj-gsmm-split\'></li>");
document.writeln("                <li id=\'dj-gsmm-search\'>");
document.writeln("                    <form action=\'\' class=\'form-check-inline\'>");
document.writeln("                        <input type=\'text\' class=\'form-control\' placeholder=\'搜索商店\'>");
document.writeln("                        <button type=\'submit\' class=\'btn btn-primary\'><i class=\'fa fa-search\'></i></button>");
document.writeln("                    </form>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script src=\'lib/jQuery/jQuery.js\'></script>");
document.writeln("<script src=\'lib/bootstrap-4.3.1-dist/js/bootstrap.js\'></script>");
document.writeln("<script src=\'lib/bootstrap-4.3.1-dist/js/bootstrap.bundle.js\'></script>");
document.writeln("<script src=\'js/dj-general.js\'></script>");
document.writeln("</body>");
document.writeln("</html>");